name: Main

on:
  push:
    branches:
      - master
  pull_request:

jobs:
  rust:
    runs-on: ubuntu-latest
    steps:
      - name: Set up Rust
        uses: hecrj/setup-rust-action@v1
        with:
          components: rustfmt
          rust-version: stable
      - uses: actions/checkout@v1
      - run: cargo fmt --all -- --check
      - run: cargo check --all
